#!/usr/bin/env python

import os
import sys

if __name__ == "__main__":
    sys.path.append(os.path.join(os.path.join(os.getcwd(), os.path.dirname(__file__)), '..'))
    from i2fhirb2.conf_file import conf_file
    conf_file(sys.argv[1:])
